## 基本操作

内置列表不可以进行运算
numpy的就可以
如果是array和数操作，那么就是该数字与每个元素操作
如果是两个array操作，那么两个array必须同形状
创建array时，所有元素必须是同一类型，如果有不同类型，会向下转换：int->float->str
type输出类型，其它属性输出相应的参数
切片操作普普通通，维度之间都在一个[]中，逗号分隔
字符串叫object
=操作实际上引用，指向的是同一个，如果希望不同，应该用copy方法

In [ ]:
import numpy as np


a = [1, 2, 3, 4, 5]
# a += 1  # TypeError: 'int' object is not iterable

a = np.array([6, 7, 8, 9, 10])
a += 1  # [7 8 9 10 11]
b = np.array([11, 12, 13])
# a + b  # ValueError: operands could not be broadcast together with shapes (5,) (3,)

c = np.array(a)
d = np.array([[14, 15, 16], [17, 18, 19]])

print(np.array([20, 21, '22']))
print(np.array([23, 24, 25.0]))
print(type(d), d.dtype, d.size, d.ndim, d.shape)
e = np.array([[26, 27, 28], [29, 30, 31], [32, 33, 34]])
print(e[0:2, 0:2])
f = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]], dtype=bool)
print(f, e[f])
print(e[np.random.rand(3, 3) > 0.5])
print(e[np.where(e > 30)])
g = np.array([35, 36, 37])
h = np.array([38, 39, 40])
print(g > h, np.logical_and(g, h))
print(np.array([41, 42, 43], dtype=np.float32))
print(np.array([44, 45, 46], dtype=object))
print(np.asarray(e, dtype=np.float32))
i = h  # reference
j = h.copy()  # copy
print(np.sum(e), np.sum(e, axis=0), np.sum(e, axis=1))
print(np.mean(e), np.mean(e, axis=0), np.mean(e, axis=1))
print(np.std(e), np.std(e, axis=0), np.std(e, axis=1))
k = np.array([[1, 2], [3, 4]])
l = np.array([[5, 6], [7, 8]])
print(np.multiply(k, l))  # element-wise multiplication
print(np.dot(k, l))  # matrix multiplication


## 常用模块

In [54]:
m = np.array([[1.5, 1.3, 7.5], [5.6, 7.8, 1.2]])
print(np.sort(m), np.sort(m, axis=0), np.sort(m, axis=1))
print(np.linspace(0, 10, 11))
print(np.searchsorted())


[[1.3 1.5 7.5]
 [1.2 5.6 7.8]] [[1.5 1.3 1.2]
 [5.6 7.8 7.5]] [[1.3 1.5 7.5]
 [1.2 5.6 7.8]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
